main/urls.py
from django.urls import path, re_path, include
from main.views import (
    landing,
    postData
)
urlpatterns = [
  path(r'', landing, name="landing"),
  path(r'post/data/', postData, name ='post_data'),
]

snippetHighlighter/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('main.urls', 'main'), namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

admin.site.site_header = 'SyntaxHighlighter Administrator@Pius_Lucky'
admin.site.site_title = 'SyntaxHighlighter Administrator@Pius_Lucky'

main/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from .utils import BeautifyCode, DefaultStyle
from urllib.parse import unquote
from django.http import JsonResponse


def landing(request):
  template = "index.html"
  lexer_object = get_all_lexers()
  lexers = [(each_lang[1][0], each_lang[0]) for each_lang in lexer_object]
  editor_styles = sorted(get_all_styles())
  context = {
    "lexers":lexers,
    "editor_styles":editor_styles
  }
  return render(request, template, context)


def postData(request):
  if request.method == 'POST' and request.is_ajax():
    textarea_field = [] 
    for key in request.POST:  
      textarea_field.append(request.POST[key])
    textarea_field = unquote(textarea_field[0].split("&")[-1].split("=")[-1])
    defaults = {
      "language": "js", 
      "style": "default",
      "type": "dark",
      "git": "true",
      "lnb": "false",
      "bdclr": "rgb(92, 77, 92);",
      "bdwidth": "1rem .1rem 1rem .1rem",
      "bdr": ".7rem",
      "pdd": "1rem"
    }
    
    def cookieRequest(name, val):
      cookie_request = request.COOKIES[name] or defaults[val]
      return cookie_request

    lexer = cookieRequest("CurrentLanguage", "language")
    style = cookieRequest("CurrentStyle", "style")
    line_number = cookieRequest("LineNumber", "lnb")
    line_number_color = cookieRequest("LineNumberColor", "type")
    generator_initial_text = cookieRequest("GeneratorInitialText", "git")
    border_color = cookieRequest("BorderColor", "bdclr")
    border_width = cookieRequest("BorderWidth", "bdwidth")
    border_radius = cookieRequest("BorderRadius", "bdr")
    padding = cookieRequest("Padding", "pdd")

    if generator_initial_text == "true":
      generator_initial_text = True
    else:
      generator_initial_text = False

    if line_number == "true":
      line_number = True
    else:
      line_number = False

    get_new_styles = DefaultStyle(border_color, border_width, padding, border_radius)
    final_styles = get_new_styles.get_style()
    beautifier_object = BeautifyCode(textarea_field, lexer, {}, style, line_number, final_styles, generator_initial_text)
    code_beautify = beautifier_object.getBeautifier()
    html = code_beautify["html"]
    theme_background = code_beautify["theme_background"]
    upper_style = code_beautify["css_styles"]   
    context = {
      "html_code":html,
      "lexer":lexer,
      "style":style,
      "line_number":line_number,
      "custom_border":final_styles,
      "line_number_color":line_number_color,
      "upper_style":upper_style,
      "theme_background":theme_background
    }
    return JsonResponse({"success":True, "data":context}, status=200)
  return JsonResponse({"success":False}, status=400)


def csrf_byepass(request, reason=""):
    # return same page
    return redirect(request.META['HTTP_REFERER']) 


  

templates/extras/extra.html
<script type="text/javascript">
    $(".central_form").submit(function(e) {
        e.preventDefault();
        var serialized_form = $(this).serialize();
        $(".s-button1").addClass("hide-submitBtn")
        $(".s-button2").addClass("show-submitBtn")
        $(".code-copy").html(`
           <button class="copy-btn">
               <svg class="svg-copy svg-1" viewBox="0 0 24 24" focusable="false" role="presentation" aria-hidden="true" class="css-yxiis9"><path fill="currentColor" d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"></path></svg><svg class="svg-copy svg-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" style="width: 1.25rem; margin-right: 0.5rem;"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>&nbsp;<span class="large-screen copied-text">Copy Code to Clipboard</span><span class="small-screen copied-text">Copy Code</span><span class="replaced-text">Copied successfully!</span>
           </button>
        `)
        $(".scroll_top").addClass("hide-copy-btn")
        $('.click_code').addClass("underline_me")
        $.ajax({
            type: "POST",
            url: "{% url 'main:post_data' %}",
            data: {serialized_form, csrfmiddlewaretoken: "{{csrf_token}}"},
            dataType: "json",
            success: function(success_data) {
                const html_code = $(success_data.data.html_code)
                const upper_style = `${success_data.data.upper_style}`
                const theme_background = `${success_data.data.theme_background}`
                const comment_check = $(success_data.data.html_code).length
                line_number_check = `${success_data.data.line_number}`
                line_number_color_check = `${success_data.data.line_number_color}`  
   
                if(line_number_check == "true"){
                  const old_pre = '<table><tbody><tr><td><pre style="margin: 0; line-height: 125%">'
                  if(line_number_color_check == "light"){
                   var new_pre = '<table><tbody><tr><td><pre style="margin: 0; line-height: 125%; color: rgba(224, 217, 236, 0.5)!important; padding-right: 1.5rem;">'
                  }else{
                   var new_pre = '<table><tbody><tr><td><pre style="margin: 0; line-height: 125%; padding-right: 1.5rem;">'
                  }  
                  const open_upper_div = `<div style="background:${theme_background}; ${upper_style}">`
                  const close_upper_div = `</div>`

                  if(comment_check > 1){
                    const div_pre = html_code[2].innerHTML
                    html_code[2].innerHTML = div_pre.replace(old_pre, new_pre);
                    const pre = html_code[2].innerHTML              
                    const first_comment = `<!-- ${html_code[0].textContent} -->`
                    const last_comment = `<!-- ${html_code[4].textContent} -->`
                    const new_html = `${first_comment} ${open_upper_div} ${pre} ${close_upper_div} ${last_comment}`
                    $(".code-content").text(new_html).removeClass('hide-copy-btn')
                  }else{
                    const div_pre = html_code[0].innerHTML
                    html_code[0].innerHTML = div_pre.replace(old_pre, new_pre);
                    const pre = html_code[0].innerHTML 
                    const new_html =  `${open_upper_div} ${pre} ${close_upper_div}`
                    $(".code-content").text(new_html).removeClass('hide-copy-btn')
                  }
                }else{
                  $(".code-content").text(`${success_data.data.html_code}`).removeClass('hide-copy-btn')
                }

                $('.modal-code').addClass('show-modal')
                $('.shield').addClass('show-modal')
                $('body').addClass('overflow-stopped')
                $('html').addClass('html-paused')
                $(window).scrollTop(0)
                const modalHeight = $(".modal-code")[0].clientHeight
                const modalWidth = $(".modal-code")[0].clientWidth
                if(modalHeight || modalWidth != 0){
                    $(".s-button1").removeClass("hide-submitBtn")
                    $(".s-button2").removeClass("show-submitBtn")
                    window.addEventListener('click', function(event){
                        try {
                          if(document.getElementsByClassName("show-modal")[0].contains(event.target)){
                            uponClose()
                          }
                        } catch(e) {
                            return;
                        }    
                    })
                }
                
                $('.code-snippet').removeClass('visible')
                $('.modal-code').removeClass('modal-code-new').removeClass("modal-code-shift")

                const line_no = `${success_data.data.line_number_color}`
                         
                $('.click_code').on("click", function(event){
                  event.preventDefault()
                  $(this).addClass('underline_me')
                  $('.code-content').removeClass('hide-copy-btn')
                  $('.code-snippet').removeClass('visible').removeClass('code-snippet-new')         
                  $('.click_snippet').removeClass('underline_me')
                  $('.modal-code').removeClass('modal-code-new').removeClass("modal-code-shift")
                })

                $('.click_snippet').on("click", function(event){
                  event.preventDefault()
                  $('.code-content').addClass('hide-copy-btn')
                  $('.code-snippet').addClass('visible').html(`${success_data.data.html_code}`).addClass('code-snippet-new')
                  $(this).addClass('underline_me')
                  $('.click_code').removeClass('underline_me')                 
                  $('.modal-code').addClass('modal-code-new').addClass("modal-code-shift")
                  
                 const line_number_color = $("table > tbody > tr > td:nth-child(1) > pre")
                  if(line_no == 'light') {
                    line_number_color.addClass("lightcolor").addClass("padding-r")
                  }else{
                    line_number_color.removeClass("lightcolor").addClass("padding-r")
                  }
                  
                })
            
                function uponClose(){
                    $('.modal-code').removeClass('show-modal')
                    $('.shield').removeClass('show-modal')
                    $('body').removeClass('overflow-stopped')
                    $('html').removeClass('html-paused')
                    $( ".copy-btn" ).remove();
                    $('.click_snippet').removeClass('underline_me')
                    $(".scroll_top").removeClass("hide-copy-btn")
                }
                
                $('.close').on("click", function(event){
                  event.preventDefault()
                  uponClose()
                })

                $(".copy-btn").on("click", function(){
                  $( ".svg-1" ).toggle();
                  if($( ".svg-1" ).is(":visible")){
                    $(".svg-2").removeClass("show-copy-btn");
                    $(".copied-text").removeClass("hide-copy-btn");
                    $(".replaced-text").removeClass("show-copy-btn");
                  }else{
                    const code = $(".code-content")[0].textContent
                    navigator.clipboard.writeText(code)         
                      $(".svg-2").addClass("show-copy-btn");
                      $(".copied-text").addClass("hide-copy-btn");
                      $(".replaced-text").addClass("show-copy-btn");
                    setTimeout(function(){
                      $( ".copy-btn" ).trigger( "click" );          
                    },2000);
                  } 
                  })
            },
            error: function(error_data) {
                   console.log(error_data)                  
                }
        })

    })
</script>